name: hello-world
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: create
        run: |
          echo "Firmware binaries"
          echo "tools packages"
      - name: Build
        run: |
          echo "hardware tools"
      - name: Release
        run: |
          echo "Firmware AI chips steps"
          echo "AMD design"