name: hello-world
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: create
        run: |
        echo "firmware binaries"
        echo "tools packages"
      - name: Build
        run: |
        echo "hardware tools"
      - name: Release
        run: |
        echo "Firmware AI chips steps"
        echo "AMD design"